### ISSUE TITLE
build.py errors with " __init__() got an unexpected keyword argument 'text'"

### ISSUE THREAD

**Issue by Jummit** [SIsilicon/GDNative-Helper#7]
When I try to build a library, build.py errors with this stack trace:
```
building library '--snip--' (linux, 32, debug).
 Generating binding library...
Traceback (most recent call last):
  File "/home/jummit/.config/godot/native_languages/C++/build.py", line 109, in <module>
    "-j%s" % multiprocessing.cpu_count()
  File "/home/jummit/.config/godot/native_languages/C++/build.py", line 18, in run_commands
    print(subprocess.check_output(args, shell=(os.name == "nt"), text=True, cwd=cwd))
  File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'text'
```

Removing the `text=True` fixes it.

**Comment by Jummit** [comment]
Updating from python 3.6 to 3.7 fixed the issue.
